apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/monitoring/prometheus
  - ../../infrastructure/monitoring/grafana
  - ../../infrastructure/monitoring/loki
  - ../../infrastructure/monitoring/fluentbit
  - ../../infrastructure/observability/otel-operator
