apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.39.0
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: flux-system
  interval: 1m
  values:
    manager:
      collector:
        enabled: true
