apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: 7.3.9
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1m
  values:
    service:
      type: ClusterIP
    adminPassword: "admin"
    persistence:
      enabled: true
      size: 1Gi
