apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: 5.41.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1m
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 1Gi
    backend:
      replicas: 1
    read:
      replicas: 1
    write:
      replicas: 1
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - loki
              topologyKey: "kubernetes.io/hostname"


