apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: monitoring
spec:
  chart:
    spec:
      chart: fluent-bit
      version: 0.46.8
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  interval: 1m
  values:
    service:
      type: ClusterIP
